# Generated by Django 5.0.6 on 2026-04-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activite',
            options={'ordering': ['-date'], 'verbose_name': 'Activité'},
        ),
        migrations.AlterModelOptions(
            name='annonce',
            options={'ordering': ['-date_publication'], 'verbose_name': 'Annonce'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['ordre'], 'verbose_name': 'FAQ'},
        ),
        migrations.AlterField(
            model_name='activite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
